name: VotifierScripts
main: com.dumptruckman.minecraft.votifierscripts.VotifierScripts
version: maven-version-number
author: dumptruckman
depend: [Votifier]
softdepend: [Vault]

commands:
  vstest:
    description: Tests the primary script file
    usage: /<command> <player>
    permission: votifierscripts.test

permissions:
  votifierscripts.test:
    default: OP